import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrainCircuit, BookOpen, FlaskConical, Gauge, GraduationCap, LayoutDashboard, Menu, Newspaper, Radar, Search, Sigma, Terminal, X} from 'lucide-react';
import './styles.css';

const sections=[
 {group:'Daily',items:[['Dashboard',LayoutDashboard],['AI Faculty',BrainCircuit]]},
 {group:'Education',items:[['Curriculum',GraduationCap],['Practice & Exams',Terminal],['Mathematics & Proof',Sigma]]},
 {group:'Research',items:[['Research Observatory',BookOpen],['Research & Model Lab',FlaskConical],['Knowledge Graph',Radar]]},
 {group:'Intelligence',items:[['AI Intelligence',Newspaper],['Technology Radar',Radar],['Open Source Radar',BookOpen]]},
 {group:'Record',items:[['GPA Engine',Gauge],['Reports & Analytics',Radar],['Portfolio',BookOpen]]}
];
const cards=[['Current GPA','3.82 / 4.00','↑ 0.14 this term'],['Courses','6 active','18 credits'],['Research','3 active','1 experiment running'],['Streak','12 days','Best: 18 days']];
function App(){const [active,setActive]=useState('Dashboard');const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const nav=(name:string)=>{setActive(name);setOpen(false)};return <div className="app">
 <aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="mark">CS</div><div><b>CS Nexus</b><span>Institute of Computation</span></div><button className="close" onClick={()=>setOpen(false)}><X size={18}/></button></div><nav>{sections.map(s=><div className="navgroup" key={s.group}><label>{s.group}</label>{s.items.map(([name,Icon]:any)=><button key={name as string} className={active===name?'navitem active':'navitem'} onClick={()=>nav(name as string)}><Icon size={16}/>{name as string}</button>)}</div>)}</nav></aside>
 <main><header><button className="mobile" onClick={()=>setOpen(true)}><Menu size={18}/></button><div><small>CS NEXUS / WORKSPACE</small><h1>{active}</h1></div><div className="headerActions"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search nexus"/><kbd>⌘K</kbd></div><div className="avatar">SD</div></div></header>
 <section className="content"><div className="hero"><div><small>MONDAY · COMPUTATION LAB</small><h2>Build. Study. Research.</h2><p>A personal operating system for serious computer science work.</p></div><button className="primary" onClick={()=>nav('Curriculum')}>Continue curriculum</button></div>
 <div className="metrics">{cards.map(c=><div className="metric" key={c[0]}><span>{c[0]}</span><strong>{c[1]}</strong><em>{c[2]}</em></div>)}</div>
 <div className="grid"><section className="panel"><div className="panelhead"><div><small>THIS WEEK</small><h3>Learning plan</h3></div><button onClick={()=>nav('Curriculum')}>Open curriculum →</button></div>{['Algorithms & Data Structures','Probability for ML','Computer Architecture','PyTorch Foundations'].map((x,i)=><div className="row" key={x}><span className="index">0{i+1}</span><div><b>{x}</b><p>{['Graphs, heaps, amortized analysis','Random variables, distributions, Bayes','ISA, caches, pipelines, memory','Tensors, autograd, training loops'][i]}</p></div><span className="tag">{['72%','61%','38%','24%'][i]}</span></div>)}</section>
 <section className="panel"><div className="panelhead"><div><small>RESEARCH DESK</small><h3>Active work</h3></div><button onClick={()=>nav('Research & Model Lab')}>Lab →</button></div><div className="research"><div className="pulse"></div><div><b>Transformer ablation study</b><p>12 experiments queued · last run 4m ago</p></div></div><div className="research"><div className="pulse dim"></div><div><b>Small language model</b><p>Architecture notes · 7 citations</p></div></div><div className="research"><div className="pulse dim"></div><div><b>Edge vision benchmark</b><p>3 models · Raspberry Pi target</p></div></div></section></div>
 <div className="bottom"><section className="panel"><div className="panelhead"><div><small>INTELLIGENCE FEED</small><h3>What matters now</h3></div><button onClick={()=>nav('AI Intelligence')}>View all →</button></div><article><span className="source">RESEARCH</span><b>Reasoning models are changing how agents plan</b><p>Read, annotate, reproduce. Treat papers as engineering inputs.</p></article><article><span className="source">OPEN SOURCE</span><b>New inference tooling cuts local model latency</b><p>Compare benchmarks before adopting a stack.</p></article></section><section className="panel quick"><small>COMMAND CENTER</small><h3>Next action</h3><p>Complete the next curriculum checkpoint, then log one research experiment.</p><button className="primary full" onClick={()=>nav('Practice & Exams')}>Start 45-minute session</button></section></div>
 </section></main></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
